ui-composition/Consumer/Models/CreateProductViewModel.cs
using Common;
using System;

namespace Consumer.Models
{
    public class CreateProductViewModel
    {
        public Product Product { get; set; }
        public Star Star { get; set; }
    }
}

ui-composition/Consumer/Models/ErrorViewModel.cs
using System;

namespace Consumer.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ui-composition/Consumer/Controllers/HomeController.cs
using Common;
using Common.Data;
using Consumer.Commands;
using Consumer.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace Consumer.Controllers
{
    public class HomeController : Controller
    {
        ProductServiceCommand _productServiceCommand;

        public HomeController(ProductServiceCommand productServiceCommand)
        {
            _productServiceCommand = productServiceCommand;
        }
        // GET api/values
        [HttpGet]
        public async Task<IActionResult> IndexAsync()
        {
            var result = await _productServiceCommand.ExecuteAsync(CancellationToken.None);
            if (result == null || !result.Any())
            {
                return View("NoContent");
            }
            return View(result);
        }
    }
}

ui-composition/Consumer/ViewComponents/CategoryViewComponent.cs
using Consumer.Commands;
using Microsoft.AspNetCore.Mvc;
using System.Threading;
using System.Threading.Tasks;

namespace Consumer.ViewComponents
{
    public class CategoryViewComponent : ViewComponent
    {
        CategoryServiceCommand _categoryServiceCommand;

        public CategoryViewComponent(CategoryServiceCommand categoryServiceCommand)
        {
            _categoryServiceCommand = categoryServiceCommand;
        }
        public async Task<IViewComponentResult> InvokeAsync(int categoryId)
        {
            _categoryServiceCommand.CategoryId = categoryId;
            var result = await _categoryServiceCommand.ExecuteAsync(CancellationToken.None);
            return View(result);
        }
    }
}

ui-composition/Consumer/ViewComponents/PriceViewComponent.cs
using Consumer.Commands;
using Consumer.Commands.Collapsers;
using Microsoft.AspNetCore.Mvc;
using System.Threading;
using System.Threading.Tasks;
using System.Linq;
using System.Collections.Generic;

namespace Consumer.ViewComponents
{
    public class PriceViewComponent : ViewComponent
    {
        MultiPriceCommandCollapser _collapser;
        CurrencyServiceCommand _currencyServiceCommand;

        public PriceViewComponent(MultiPriceCommandCollapser collapser, CurrencyServiceCommand currencyServiceCommand)
        {
            _collapser = collapser;
            _currencyServiceCommand = currencyServiceCommand;
        }
        public async Task<IViewComponentResult> InvokeAsync(int productId)
        {
            _collapser.ProductId = productId;
            var result = await _collapser.ExecuteAsync(CancellationToken.None);
            var currencyCookie = Request.Cookies.FirstOrDefault(x => x.Key == "SelectedCurrency" && !string.IsNullOrWhiteSpace(x.Value));
            if (currencyCookie.Equals(default(KeyValuePair<string, string>)))
            {
                return View(result);
            }

            var currencies = await _currencyServiceCommand.ExecuteAsync(CancellationToken.None);
            if (currencies != null && currencies.Any(x => x.Id == currencyCookie.Value))
            {
                var usd = currencies.First(x => x.Id == currencyCookie.Value);
                result.Amount = result.Amount / usd.Bid;
                result.Currency = usd.Symbol;
            }

            return View(result);
        }
    }
}

ui-composition/Consumer/ViewComponents/StarViewComponent.cs
using Consumer.Commands;
using Microsoft.AspNetCore.Mvc;
using System.Threading;
using System.Threading.Tasks;

namespace Consumer.ViewComponents
{
    public class StarViewComponent : ViewComponent
    {
        StarServiceCommand _starServiceCommand;

        public StarViewComponent(StarServiceCommand starServiceCommand)
        {
            _starServiceCommand = starServiceCommand;
        }
        public async Task<IViewComponentResult> InvokeAsync(int productId)
        {
            _starServiceCommand.ProductId = productId;
            var result = await _starServiceCommand.ExecuteAsync(CancellationToken.None);
            return View(result);
        }
    }
}

ui-composition/Consumer/Views/Home/IndexAsync.cshtml
@using Common
@model IList<Product>
<div class="row">
    <div class="col-md-3">
        <h4>Ürün Adı</h4>
    </div>
    <div class="col-md-3">
        <h4>Kategori</h4>
    </div>
    <div class="col-md-3">
        <h4>Fiyat</h4>
    </div>
    <div class="col-md-3">
        <h4>Beğenilme</h4>
    </div>
</div>
@foreach (var item in Model)
{
<div class="row">
    <div class="col-md-3">
        <h4>@item.ProductName</h4>
    </div>
    <div class="col-md-3">
        <h4>@await Component.InvokeAsync("Category", new { categoryId = item.CategoryId })</h4>
    </div>
    <div class="col-md-3">
       <h4>@await Component.InvokeAsync("Price", new { productId = item.Id })</h4>
    </div>
    <div class="col-md-3">
        <h4>@await Component.InvokeAsync("Star", new { productId = item.Id })</h4>
    </div>
</div>
}

ui-composition/Consumer/Views/Home/NoContent.cshtml
<div class="row">
    <div class="col-md-12">
        <h1>Ürün servisine ulaşılamıyor!</h1>
        <h2>Lütfen daha sonra tekrar deneyiniz.</h2>
    </div>
</div>

ui-composition/Consumer/Views/Shared/Components/Category/Default.cshtml
@model Common.Category
@if(Model != null) {
    <span>@Model.Name</span>
} else {
    <span> - </span>
}

ui-composition/Consumer/Views/Shared/Components/Price/Default.cshtml
@model Common.Price
@if(Model != null) {
    <span>@Model.Amount.ToString("N2")</span> <span>@Model.Currency</span>
} else {
    <span> - </span>
}

ui-composition/Consumer/Views/Shared/Components/Star/Default.cshtml
@using Common
@model Star
@{
    if(Model != null) {
        var count = 0;
        while(count < Model.StarCount)
        { 
            <span>✌️</span>
            count++;
        }
    } else {
        <span class="no-comment-warn"><i>Henüz hiç değerlendirme yok&nbsp;</i>🙁</span>
    }
}

ui-composition/Consumer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Consumer</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Consumer</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Consumer</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>